name: "Python"
description: "Install python and run test"
inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.9"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install poetry
      run: curl -sSL https://install.python-poetry.org | python3 -
      shell: bash
    - name: Install python dependencies
      run: poetry install
      shell: bash
    - name: Complexity
      run: poetry run make complexity
      shell: bash
    - name: Lint
      run: poetry run make lint
      shell: bash
    - name: Test
      run: poetry run make test --cov-fail-under=80 --cov=src tests
      shell: bash
