name: "Node"
description: "Setup node"
inputs:
  node-version:
    description: "Node version to use"
    required: false
    default: "16"
  github-access-token:
    description: "A Github Access Token to download private dependencies"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
    - name: Cache dependencies
      uses: actions/cache@v2
      id: cache-dependencies
      with:
        path: node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Install node dependencies
      run: npm ci
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.github-access-token }}
